### ISSUE TITLE
Feature Request:  Please Allow msg.payload to be passed to this LINE node.

### ISSUE THREAD

**Issue by unixneo** [okhiroyuki/node-red-contrib-line-notify#12]
Thank you for this node.

Can you please modify it so we can send the LINE Notify node a message (from msg. payload for example) instead of having a static message per node?

Thank you.

**Comment by okhiroyuki** [comment]
Thank you for your request.

Is your request the same as the issue below?
https://github.com/okhiroyuki/node-red-contrib-line-notify/issues/9

**Comment by unixneo** [comment]
Hi.

Yes, this is the same idea.   Your LINE notification node should receive ```msg.payload``` on the input so we can set the message from the flow.


Thank you!

**Comment by okhiroyuki** [comment]
Since there are multiple same requests, it was decided that msg.payload should be supported.

**Comment by unixneo** [comment]
Thanks!  So you will add input to your node so we can wire msg flows into your LINE node soon?

**Comment by okhiroyuki** [comment]
@unixneo 
released v3.0.0

**Comment by unixneo** [comment]
Yes, Tried version 3.0. It does not work any differently.

msg.payload is not sent.... nothing has changed except there is a new "in link" added, but it still does not accept a msg object and send the payload as we have requested.

Thanks.

**Comment by okhiroyuki** [comment]
@unixneo 
please share your code.

**Comment by unixneo** [comment]
```
[{"id":"34e48d27.986792","type":"function","z":"21dff30d.cdd83c","name":"Bird Logic","func":"var onoff =global.get('onoff') || 'on';\nlet personDetected = false;\nlet newMsg = {};\nvar chat = 727630977;\nvar type = \"message\";\nvar message = \"\";\nvar count = 0;\nvar score = 0.0;\nvar onoi = [\"vase\",\"bed\",\"chair\", \"couch\", \"bench\",\"microwave\",\"bottle\",\"cup\"];\n\nif(onoff ==\"on\" ||onoff ==\"debug\")\n{\nfor (let object of msg.payload) {\n    if (object.class.length >  2 ) {\n        if (onoi.includes(object.class)) {\n        }\n        else {\n        count++;\n        score = (100*object.score).toFixed(1);\n         message = 'CamBot detected a \"'+ object.class+'\" with '+score+'% confidence.';\n         newMsg = {payload:{chatId:chat,type:type,content:message}};\n        //console.log(newMsg.payload);\n        if(object.class == 'bird' || true){\n          node.send([ [ newMsg] ]);\n        }\n        }\n    }\n}\n\nif(count < 1 &&  onoff == \"debug\"){\n    message = 'CamBot detected nothing!';\n       newMsg = {payload:{chatId:chat,type:type,content:message}};\n       node.send([ [ newMsg] ]);\n}\n}\n","outputs":1,"noerr":0,"x":970,"y":240,"wires":[[]]}]
```

**Comment by unixneo** [comment]
It's easy to test and you don't need my code, but here is it.

Just inject a msg object into your node; and it should send msg.payload.

It does not.

**Comment by okhiroyuki** [comment]
@unixneo 
Is what you requested what this sample shows?
If you change the character string of the inject node, you can notify by LINE.

```
[{"id":"ade99916.44d898","type":"line-notify","z":"8a8dfd93.34e31","name":"","message":"","contentType":"message","imageThumbnail":"","imageUrl":"","sticker":"default","stickerPackageId":"1","stickerId":"1","silent":false,"creds":"5b40638f.d3e5dc","x":460,"y":280,"wires":[["206c67c4.05c548"]]},{"id":"49be5abb.8854d4","type":"inject","z":"8a8dfd93.34e31","name":"","topic":"","payload":"test","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":270,"y":280,"wires":[["ade99916.44d898"]]},{"id":"206c67c4.05c548","type":"debug","z":"8a8dfd93.34e31","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":630,"y":360,"wires":[]},{"id":"5b40638f.d3e5dc","type":"linetoken","z":"","name":""}]
```

**Comment by unixneo** [comment]
Sorry, I am not trying to sound anti-social; but do you actually use Node-RED?

I ask this because what we are asking is very basic to Node-RED.

Node-RED is a "flow-based" model; and so messages move in the flow using a msg object.

In your node, the msg object should be accepted, added to your LINE message when sent, and also appended to your output so it can be seen on output with a debug node.   

This is basic "Node-RED 101" programming.

**Comment by unixneo** [comment]
Thanks.  It works; but please add the payload to the output of your node:

Now:

```
object
status: 200
message: "ok"
```

Should be:

```
object
status: 200
message: "ok"
payload: "my message content from msg.payload"
```
Thanks

**Comment by okhiroyuki** [comment]
@unixneo 
Do you want to receive the contents of the input message as msg.payload as the return value?
Indeed, I think it should be.

**Comment by unixneo** [comment]
Yes, normally nodes should have the input msg object added to the output so we can pass the output to another node, especially a debug node.

If you look at your example output:

```msg : Object
object
_msgid: "28296f4.8a94a9"
topic: ""
payload: object
status: 200
message: "ok"
``

You should include the original msg.payload, like this:

```
msg : Object
object
_msgid: "28296f4.8a94a9"
topic: ""
payload: object
status: 200
message: "ok"
payload:"hello world"
```

**Comment by okhiroyuki** [comment]
@unixneo 
## Proposal:
msg.payload.message is always OK, so delete it.
Also, status is separated from msg.payload.

Now:
```
msg.payload = {
   status: 200,
   message: "ok"
}
```

Update: 
```
msg.payload = "my message content from msg.payload",
msg.status = 200
```

**Comment by unixneo** [comment]
Looks good.

Yes, you don't need "ok" if you have msg.status, but no harm in keeping it in object, like this:

```msg.payload = {
   status: 200,
   message: "ok",  // or "success" or "message sent"
   payload: "my message content from msg.payload"
}
```


But I see if the token is wrong, the output is:

```
msg : string[35]
"Request failed with status code 401"
```
But shouldn't the output be:

```msg  = {
message: "Request failed with status code 401",
payload = "my message content from msg.payload",
status: 401
}
```

Something like that, so the errors are in the same format as the success?

**Comment by okhiroyuki** [comment]
>"Request failed with status code 401"

If the token is an error, the response of the node will be exactly as described because the error method is used instead of the normal send method.

<img width="1335" alt="スクリーンショット 2020-03-08 12 37 54" src="https://user-images.githubusercontent.com/23309/76156164-ad7e7f00-6139-11ea-8b8f-2812b64e31f9.png">

**Comment by unixneo** [comment]
OK

I would prefer it has the same format in the error case; but it is not important and not necessary to change the error case if you do not want to or it is not possible.

Thanks!

Getting the message payload in the output, is good already and so thanks and for that and looking forward to it.

Great job.

**Comment by okhiroyuki** [comment]
Thank you for comment.

>I would prefer it has the same format in the error case.

You're right.

## Proposal
In the case of an error, I thought that there was no problem with the error message in msg.payload.
how is it?

New Error Handling:
```
msg.payload = "error message for line server",
msg.status = 401
```

**Comment by unixneo** [comment]
Better.

Thanks.

**Comment by unixneo** [comment]
Actually, to be honest... 

It is better to pass the original msg payload when there is error; and put the error message in a different variable:

```msg.error = "error message for line server",
msg.payload = "original message from input",
msg.status = 401
```

**Comment by okhiroyuki** [comment]
Thank you for comment.

Looking at various Node-RED standard nodes, msg.payload does not always return the input msg.payload.
In this node, if an error occurs, an error message is passed to msg.payload.

**Comment by unixneo** [comment]
Yes, it depend on the module / node and also your plans for the future.

Thank you for you consideration and for this nice Notify node.

**Comment by okhiroyuki** [comment]
@unixneo 
released 3.1.0.
Please try it.

**Comment by unixneo** [comment]
I will... but so far, 3.1.0 does not show up in Node-RED.

I tried on two NR instances, and only see:

```
node-red-contrib-line-notify
3.0.0
```

**Comment by okhiroyuki** [comment]
@unixneo 
Try the following npm commands:

```
npm i node-red-contrib-line-notify@3.1.0
```

**Comment by unixneo** [comment]
It's OK now...  Maybe just needed time to sync with Node-RED.

Yes, I tested and works great.

THANK YOU.

You can close if you want :)

**Comment by unixneo** [comment]
+1 STAR :)

**Comment by unixneo** [comment]
Working AWESOME.

Thanks you again for this modification!

**Comment by unixneo** [comment]
Prologue:

https://discourse.nodered.org/t/improvements-to-node-red-contrib-line-notify-v3-1-0/22796
