### ISSUE TITLE
Version 3.0 Does Not Send Messages from Flow

### ISSUE THREAD

**Issue by unixneo** [okhiroyuki/node-red-contrib-line-notify#14]
Please do not close an issue raised until it is confirmed fixed by the people who post the issue. Thanks.  

You asked us to "try v3.0" and closed the issue before we replied.  I would appreciate it if you would kindly not close open issues you have asked us to try, until we (the users who requested the feature or provide bug report) confirm it is fixed.

Now, I have already tried your v3.0 code, and it does not work at any differently than the prior version.

When we send it a msg object (like any other node in a flow) your LINE does not to send that msg.payload object.

**Comment by okhiroyuki** [comment]
Sorry. Reopen

**Comment by okhiroyuki** [comment]
@unixneo 
Please close here after confirming that the issue has been reopened.
