### ISSUE TITLE
ヘルプは英語で見えないんです

### ISSUE THREAD

**Issue by oozorataiyou** [okhiroyuki/node-red-contrib-line-notify#33]
すみません
ヘルプは英語で見えないんです
<img width="314" alt="Screenshot 2020-07-25 at 17 12 49" src="https://user-images.githubusercontent.com/3457550/88453685-d9599180-ce9b-11ea-8c45-f1ee8b38b4e6.png">

英語でlocalesのフォルダ"line-notify.html"の名は間違えた
あまり自信がないから試してください

ちょっと失礼ですけど
"line-notify.html"に`<h3>Detials</h3>`は間違えた`<h3>Details</h3>`です
"For further details ~~of~~ see ..."

私の日本語が下手からごめんなさい
これを作成していただいてありがとう

**Comment by okhiroyuki** [comment]
@oozorataiyou 

こんにちは、教えていただき、ありがとうございます。
タイポ修正します。

**Comment by okhiroyuki** [comment]
@oozorataiyou 

The modified version has been published to npm.
Please try it out.

**Comment by oozorataiyou** [comment]
ok thank you very much 👍
