### ISSUE TITLE
add msg.payload of before node to message

### ISSUE THREAD

**Issue by hkjang** [okhiroyuki/node-red-contrib-line-notify#9]
Thank you for your open source contribution.

It would be nice if i can add msg.payload to the message to send LINE.

I'm not sure if this is a good example...

```js
            let send_message;
            if(msg.data !== undefined && typeof msg.data !== 'undefined'){
              if(msg.data.application_name !== undefined && typeof msg.data.application_name === 'string'){
                  node.application_name = msg.data.application_name;
                  send_message = '[' + node.message + '][' + node.application_name + '][' + msg.topic + '] / ' + msg.payload;
              }
            }else{
              send_message = '[' + node.message + '][' + msg.topic + '] / ' + msg.payload;
            }
```

Thanks.

**Comment by okhiroyuki** [comment]
Thank you for your suggestion.

Currently, msg.message is used.
Any suggestions to change this to msg.payload?

https://github.com/okhiroyuki/node-red-contrib-line-notify/blob/9633509fdd338cfae93eb3ffd5c2a3f20885201d/nodes/line-notify.js#L58-L64

**Comment by hkjang** [comment]
Thanks to reply. 
Ok~ i got it ! 

In general, in my opinion, I use msg.payload in logic.
I think msg.message is good too.

**Comment by hkjang** [comment]
hello 
i have problem to send message from msg param

![image](https://user-images.githubusercontent.com/3069493/110866943-4d508900-8309-11eb-8f13-211ed245c42d.png)

**Comment by okhiroyuki** [comment]
@hkjang 
hi,

It is msg.payload, not msg.message.

https://github.com/okhiroyuki/node-red-contrib-line-notify/blob/5b55cd88263fbec73e4d0bed35d8638bcbc9be6f/nodes/line-notify.js#L63-L69

**Comment by hkjang** [comment]
oh ~ i see 
I'm sorry.. 
I had been confused by this. 

![image](https://user-images.githubusercontent.com/3069493/110867958-0499cf80-830b-11eb-934f-94b197fb5101.png)

**Comment by okhiroyuki** [comment]
@hkjang 
It is hoped that the node's help tag will help people see the information.

Also, I'm aware that it was your opinion that I switched to msg.payload.

>It would be nice if i can add msg.payload to the message to send LINE.

**Comment by hkjang** [comment]
Previously, when the parameter was only message, I thought it would be better to deliver the message by payload.

But now, more information is passed as a parameter, so...
For example, image information, thumbnail information, etc...
 
So I think msg.message is more suitable now.

sorry for inconveniencing to you.

It’s helping a lot
Thank you

**Comment by hkjang** [comment]
I think it might be good to apply both

**Comment by hkjang** [comment]
小さなコメントまで考慮していただきありがとうございます。^^

**Comment by okhiroyuki** [comment]
@hkjang 
Thank you too for all your help.

As for the node policy, I think that the main text message is handled by msg.payload, while other options are handled by specially prepared msg variable parameters.
Please see it that way.
